### ISSUE TITLE
Finish Client/Server Interaction 

### ISSUE THREAD

**Issue by philberhane** [philberhane/mmart162urlshortener#5]
Part Two

**Comment by ayyrickay** [comment]
@amyamyc @philberhane Any updates on this? (: If you can update these issues and populate git with new ones, it'll give Sarah and I an idea of how your plan moving forward. Definitely close issues as they're completed (and protip, you can reference the pull request where it got solved by typing in the hash sign and selecting the pull request number, e.g., #8 )
